### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Hannychan** [ibartomeus/BeeIT#1]
I have this error
Error: Failed to install 'BeeIT' from GitHub:
  (convertido del aviso) cannot remove prior installation of package ‘glue’

And i had to change the code to:
install.packages("devtools")
require(devtools)
install_github('ibartomeus/BeeIT')

Help is much appreciated. thanks

**Comment by ibartomeus** [comment]
It looks like it has a conflict with the package "glue", which as far as I know it's not used by BeeIT. Try uninstalling the glue package, restarting R, and see if this does the trick.

**Comment by Hannychan** [comment]
Thank you! so fast. It seems that the problem is in my computer, it started having problems with devtools now, i'll try re-installing the full program for now. But thank you so much por such quick reply!
Kind regards.
